version: "2"

services:
  web:
    build: ./web
    command: bash -c "npm i && npm start"
    volumes:
      - ./web:/web
    ports:
      - "3000:3000"
  server:
    build: ./server
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
